version: "3"

services:
  sql:
    build: ./sql
    volumes:
      - passport-local:/var/lib/mysql
    env_file:
      - ./docker-compose.env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
volumes:
  passport-local: